version: "3"
services:
    postgres:
        image: postgres:10.13
        network_mode: bridge
        container_name: postgres
        volumes: 
            - /var/lib/postgresql/docker/data:/var/lib/postgresql/data
        expose:
            - 5432
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=person
        restart: unless-stopped
    springbootapp:
        image: danilocgraciano/person:1.0
        network_mode: bridge
        container_name: springbootapp
        volumes:
            - ~/logs:/opt/app/log
        expose: 
            - 8080
        ports: 
            - 8080:8080
        restart: unless-stopped
        depends_on: 
            - postgres
        links: 
            - postgres